name: cdle-sync
on:
  schedule:
    - cron: '25 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-cdle-xdd
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync cdle-xdd
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/cdle/xdd.git"
          source_branch: "master"
          destination_branch: "cdle"
          github_token: ${{ secrets.PAT }}
